// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickets.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const purchaseTicket = `-- name: PurchaseTicket :exec
UPDATE tickets
SET status = 'sold'
WHERE id = $1 AND status = 'booked'
`

func (q *Queries) PurchaseTicket(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, purchaseTicket, id)
	return err
}

const reserveTicket = `-- name: ReserveTicket :exec
UPDATE tickets
SET status = 'booked'
WHERE id = $1 AND status = 'available'
`

func (q *Queries) ReserveTicket(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, reserveTicket, id)
	return err
}
