// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/ignisrex/tix/core/types"
)

type TicketStatus string

const (
	TicketStatusAvailable TicketStatus = "available"
	TicketStatusSold      TicketStatus = "sold"
)

func (e *TicketStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketStatus(s)
	case string:
		*e = TicketStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketStatus: %T", src)
	}
	return nil
}

type NullTicketStatus struct {
	TicketStatus TicketStatus
	Valid        bool // Valid is true if TicketStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketStatus), nil
}

type Event struct {
	ID          uuid.UUID
	Title       string
	Description string
	StartDate   time.Time
	VenueID     uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Ticket struct {
	ID           uuid.UUID
	EventID      uuid.UUID
	TicketTypeID uuid.UUID
	Status       types.TicketStatus
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type TicketType struct {
	ID          uuid.UUID
	Name        string
	Description string
	PriceCents  int32
}

type Venue struct {
	ID       uuid.UUID
	Name     string
	Location string
}
