// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickets.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const batchCreateTickets = `-- name: BatchCreateTickets :many
INSERT INTO tickets (event_id, ticket_type_id, status)
SELECT 
    $1::uuid,
    unnest($2::uuid[]),
    'available'::ticket_status
RETURNING id, event_id, ticket_type_id, status, created_at, updated_at
`

type BatchCreateTicketsParams struct {
	Column1 uuid.UUID
	Column2 []uuid.UUID
}

func (q *Queries) BatchCreateTickets(ctx context.Context, arg BatchCreateTicketsParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, batchCreateTickets, arg.Column1, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.TicketTypeID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicket = `-- name: GetTicket :one
SELECT 
    id,
    event_id,
    ticket_type_id,
    status,
    created_at,
    updated_at,
    ticket_type_name,
    ticket_type_display_name,
    ticket_type_price_cents
FROM enriched_tickets
WHERE event_id = $1 AND id = $2
`

type GetTicketParams struct {
	EventID uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) GetTicket(ctx context.Context, arg GetTicketParams) (EnrichedTicket, error) {
	row := q.db.QueryRowContext(ctx, getTicket, arg.EventID, arg.ID)
	var i EnrichedTicket
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TicketTypeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TicketTypeName,
		&i.TicketTypeDisplayName,
		&i.TicketTypePriceCents,
	)
	return i, err
}

const getTicketTypes = `-- name: GetTicketTypes :many
SELECT id, name, display_name, price_cents FROM ticket_types
`

func (q *Queries) GetTicketTypes(ctx context.Context) ([]TicketType, error) {
	rows, err := q.db.QueryContext(ctx, getTicketTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketType
	for rows.Next() {
		var i TicketType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketsForEvent = `-- name: GetTicketsForEvent :many
SELECT 
    id,
    event_id,
    ticket_type_id,
    status,
    created_at,
    updated_at,
    ticket_type_name,
    ticket_type_display_name,
    ticket_type_price_cents
FROM enriched_tickets
WHERE event_id = $1
ORDER BY ticket_type_id, id
`

func (q *Queries) GetTicketsForEvent(ctx context.Context, eventID uuid.UUID) ([]EnrichedTicket, error) {
	rows, err := q.db.QueryContext(ctx, getTicketsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnrichedTicket
	for rows.Next() {
		var i EnrichedTicket
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.TicketTypeID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TicketTypeName,
			&i.TicketTypeDisplayName,
			&i.TicketTypePriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
