// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venues.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (name, location)
VALUES ($1, $2)
RETURNING id, name, location
`

type CreateVenueParams struct {
	Name     string
	Location string
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRowContext(ctx, createVenue, arg.Name, arg.Location)
	var i Venue
	err := row.Scan(&i.ID, &i.Name, &i.Location)
	return i, err
}

const deleteVenue = `-- name: DeleteVenue :exec
DELETE FROM venues
WHERE id = $1
`

func (q *Queries) DeleteVenue(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVenue, id)
	return err
}

const getVenue = `-- name: GetVenue :one
SELECT id, name, location FROM venues
WHERE id = $1
`

func (q *Queries) GetVenue(ctx context.Context, id uuid.UUID) (Venue, error) {
	row := q.db.QueryRowContext(ctx, getVenue, id)
	var i Venue
	err := row.Scan(&i.ID, &i.Name, &i.Location)
	return i, err
}

const getVenues = `-- name: GetVenues :many
SELECT id, name, location FROM venues
ORDER BY name ASC
LIMIT $1
OFFSET $2
`

type GetVenuesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetVenues(ctx context.Context, arg GetVenuesParams) ([]Venue, error) {
	rows, err := q.db.QueryContext(ctx, getVenues, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(&i.ID, &i.Name, &i.Location); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVenue = `-- name: UpdateVenue :one
UPDATE venues
SET name = $2,
    location = $3
WHERE id = $1
RETURNING id, name, location
`

type UpdateVenueParams struct {
	ID       uuid.UUID
	Name     string
	Location string
}

func (q *Queries) UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error) {
	row := q.db.QueryRowContext(ctx, updateVenue, arg.ID, arg.Name, arg.Location)
	var i Venue
	err := row.Scan(&i.ID, &i.Name, &i.Location)
	return i, err
}
